name: Build Release ZIP

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'


jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

#      - name: Validate themes
#        run: some validation

      - name: Zip the release
        run: mkdir release && zip -r release/edgetx-themes.zip THEMES

      - name: Upload zip package
        uses: actions/upload-artifact@v3
        with:
          name: themes-latest
          path: release
          retention-days: 15
          if-no-files-found: error

  upload:
    name: Upload latest release
    needs: package
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: themes-latest
          path: release

      # - name: Display structure of downloaded files
      #   run: ls -R

      - name: Upload binaries to release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          title: "Latest Themes Package"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files: release/edgetx-themes.zip
          automatic_release_tag: 'latest'
          prerelease: false
